name: CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit Tests
        run: |
          bin/test-unit.sh
      - name: Integration Tests
        run: |
          pip3 install Flask
          cd integration && python3 server.py &
          export HURL_VERSION=$(grep version gradle.properties | cut -f2 -d"=")
          export hurl="java -jar $PWD/hurl-cli/build/libs/hurl-$HURL_VERSION.jar"
          export hurlfmt="java -jar $PWD/hurl-fmt/build/libs/hurl-fmt-$HURL_VERSION.jar"
          bin/test-integration.sh

